### ISSUE TITLE
Connection from Configurator to Arduino not possible

### ISSUE THREAD

**Issue by DerElch87** [flyandi/BitsyLED#2]
To start with, I'm feeling really bad to annoy you two times a day with problems or wishes :)

I and also a collegue from a german FPV forum are experiencing problems with the connection between the configurator and the arduino.

Configurator: 0.6.2
Firmware: 1.0.3
Arduino Nano (with old bootloader)

I changed the config.h accordingly and flashed the software.

There seems to be no connection possible, it simply outputs "connecting..." and nothing changes.

The collegue experienced the same after updating to 0.6.2 - before it worked with 0.6.0
But for him a downgrade also didn't helped.

So either there is some kind of incompadibility with one of the recent windows 10 updates or something else strange is going on.

Thanks and greetings

**Comment by flyandi** [comment]
Let me dig into it. You using just a simple Nano board, right?

**Comment by DerElch87** [comment]
Yes, should be identically to a ProMini, only with a FTDI / CH340.

Thanks

**Comment by flyandi** [comment]
OK cool - let me play around with it.

**Comment by VolkerFi** [comment]
Hello, Flyandy,

I am the user who wrote to you on the hackaday website. I meant the user DerElch87 with the same problem.
I was able to repeat the same behaviour today with an Arduino uno.

The tested Arduino nano all have an "old" bootloader. All 4 copies show the same behaviour (config.h -> arduino):
- bottle the firmware (older than 28.4.19) with the Arduino IDE -> OK
 - no connection with the configurator 0.6.0 (configured on Arduino)
- flashing the firmware (current) with the Arduino IDE -> OK
 - no connection with the configurator 0.6.2

Thank you very much for your effort.
VolkerFi

Translated with www.DeepL.com/Translator

**Comment by flyandi** [comment]
So I was playing around with and seems the EEPROM becomes corrupt and does not properly send back the data - for some reason the data itself stays correct in the EEPROM. I will fix this and make the protocol more stable - may have to rethink the protocol header with a more solid checksum

**Comment by DerElch87** [comment]
Great that you found the issue.
Looking forward for a fix :)
Thanks and BR

**Comment by VolkerFi** [comment]
That sounds good for the future.

Thanks, VolkerFi

**Comment by flyandi** [comment]
I was out for a while but will be publishing some fixes shortly here.

**Comment by net-worker** [comment]
Can you publish the fix or is this Project Dead?
Thanks 4 information and BR

**Comment by flyandi** [comment]
Alright everyone. I finally had some time to catch up on this tonight and did some stability improvement with the EEPROM. Looks like the issue is that the serial buffer was too little and too fast which caused the EEPROM not properly to store the data and also the serial buffer to choke eventually.

Firmware 1.04 and Configurator 0.6.5 are up now. Hope this will fix some stuff - it did for me on the 1.2.1 boards with the ATT84.
