### ISSUE TITLE
Configurator not filling window

### ISSUE THREAD

**Issue by NH4x4Jeep** [flyandi/BitsyLED#4]
Hi Andy!
GREAT project! I'm having a bit of trouble with the configurator, though... I ran the BitsyLED.exe from the following link:https://github.com/flyandi/BitsyLED/releases/tag/v0.6.2 The setup went fine. However, when I ran the Configurator, the screen is cut off.For Example.. If I select the Airplane (RC), then the Configurator screen appears; however, it's truncated. The TOP of the screen only shows as high as "Navigation". It's cut off above that. It's also cut off below "Serial Port". I can't see the selection box for Serial Port. I CAN tab to it, but I can't see it. I installed on Windows 7 64 bit, then realized that probably isn't supported. Then I installed on my son's Windows 10 machine and it did the same thing. Did I miss something? Am I missing a file?
![2019-06-11 18_26_51-BitsyLED Configurator](https://user-images.githubusercontent.com/4122442/59568058-7e702c80-9043-11e9-8290-34f2b9a4dd4c.jpg)
   
Please help, I'd really love to get this running! Thanks in advance!
Jon G

**Comment by flyandi** [comment]
Interesting - I don't know how that would happen but let me take a look. The interface is locked down to a specific size.. so no idea why this is happening.

**Comment by flyandi** [comment]
Finally had some time to fix this issue. Should be good now.
